# Generated by Django 4.2 on 2023-10-27 00:00

from django.db import migrations
import os

def create_default_superuser(apps, schema_editor):
    """
    Creates a default superuser if no users exist.
    """
    User = apps.get_model('auth', 'User')
    if not User.objects.exists():
        username = os.environ.get('ADMIN_USER', 'admin')
        password = os.environ.get('ADMIN_PASSWORD', 'password')
        print(f'Creating default superuser: {username}')
        User.objects.create_superuser(username=username, password=password, email='')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_superuser),
    ]
