version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=password
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 password_manager.wsgi:application"
